name: Mirror to EXOPA-OAPa

on:
  push:
    branches:
      - "**"
    tags:
      - "**"

jobs:
  mirror:
    # Esegui il mirror SOLO nel repository personale
    if: github.repository == 'Daddi14/photo-cat'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Mirror repository
        env:
          MIRROR_TOKEN: ${{ secrets.MIRROR_TOKEN_EXOPA }}
        run: |
          git push --mirror \
            "https://x-access-token:${MIRROR_TOKEN}@github.com/EXOPA-OAPa/PHOTO-CAT.git"
